---
abstract: 'Use the GMP library for Math::BigInt routines'
author:
  - Tels
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Math-BigInt-GMP
no_index:
  directory:
    - t
    - inc
requires:
  Math::BigInt: '1.9993'
  XSLoader: '0.02'
version: '1.39'
x_serialization_backend: 'CPAN::Meta::YAML version 0.016'
