---
name: Math-BigInt-GMP
author: Tels
version: 1.35
version_from: lib/Math/BigInt/GMP.pm
license: perl
distribution_type: module
generated_by: Math-BigInt-GMP version 1.35
installdirs: site
requires:
  Math::BigInt: 1.9905
  XSLoader: 0.02
