---
name: Math-BigInt-GMP
author: Tels
version: 1.26
version_from: lib/Math/BigInt/GMP.pm
license: perl
distribution_type: module
generated_by: Math-BigInt-GMP version 1.26
installdirs: site
requires:
  Math::BigInt: 1.9
  XSLoader: 0.02
