---
name: Math-BigInt-GMP
author: Tels
version: 1.20
version_from: lib/Math/BigInt/GMP.pm
license: perl
distribution_type: module
generated_by: Math-BigInt-GMP version 1.20
installdirs: site
requires:
  Math::BigInt: 1.82
  XSLoader: 0.02
